### ISSUE TITLE
helm install turing turing/turing Error: INSTALLATION FAILED

### ISSUE THREAD

**Issue by verramuktytoko** [gojek/turing#136]
I got this error during installation following this guideline https://github.com/gojek/turing/blob/main/infra/charts/turing/README.md.

**Steps**

1. helm install incubator/sparkoperator --generate-name

WARNING: This chart is deprecated
W1128 22:23:02.075723   56032 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W1128 22:23:02.080260   56032 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W1128 22:23:02.314421   56032 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W1128 22:23:02.324651   56032 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
NAME: sparkoperator-1638112978
LAST DEPLOYED: Sun Nov 28 22:23:01 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None

2. helm install turing-init turing/turing-init --namespace infrastructure --create-namespace

NAME: turing-init
LAST DEPLOYED: Sun Nov 28 22:23:53 2021
NAMESPACE: infrastructure
STATUS: deployed
REVISION: 1
TEST SUITE: None

3. helm install turing turing/turing

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Gateway" in version "networking.istio.io/v1beta1", unable to recognize "": no matches for kind "VirtualService" in version "networking.istio.io/v1beta1"]

**My local setup**
- k3d latest version https://k3d.io/v5.1.0/
- helm v3.7.1
- kubernetes v1.22.3

**Comment by ashwinath** [comment]
Hi @verramuktytoko, thanks for trying out the Helm charts. 

As a side node, step 1 is not required.

On the second step, a init job will be created. It is likely that the second step was not completed before you proceeded with step 3. Step 2 takes a while to complete.

You have to check `kubectl get pod --namespace infrastructure` to check if the init pod has finished running. Programmatically if you run it in a script, you could do `kubectl wait -n infrastructure --for=condition=complete --timeout=10m job/turing-init-init` where this is a blocking action that will only complete if the service passes (exit code 0 denotes success and other exit codes means failure of the init pod).

Once the second step is complete then step 3 should be working.

**Comment by ashwinath** [comment]
I have updated the documentation but please let me know if you still have any more queries.

**Comment by verramuktytoko** [comment]
Hi @ashwinath the deployment is succesful now
NAME: turing-init
LAST DEPLOYED: Mon Nov 29 14:28:20 2021
NAMESPACE: infrastructure
STATUS: deployed
REVISION: 1
TEST SUITE: None

but when I check the pods, there are 2 crash, 1 is pending. as a result, I cannot continue start turing API server.
`_kubectl get pod                                  
NAME                                           READY   STATUS                  RESTARTS   AGE
turing-postgresql-mlp-0                        0/1     Pending                 0          22m
turing-vault-agent-injector-5976b6c65c-685lm   1/1     Running                 0          22m
turing-postgresql-merlin-0                     1/1     Running                 0          22m
turing-postgresql-0                            1/1     Running                 0          22m
turing-merlin-567844c58-lqhwk                  1/1     Running                 0          22m
turing-vault-0                                 1/1     Running                 0          22m
turing-mlp-7cc5f9bb94-jppz7                    0/1     Init:CrashLoopBackOff   8          22m
turing-64575957bc-h5dr5                        0/1     CrashLoopBackOff        8          22m_`

**Comment by romanwozniak** [comment]
@verramuktytoko we need more information from you in order to help you to get it running. You can ignore 2 crashing pods for now as it's expected (`turing-mlp` crashes because it can establish a connection to `turing-postgresql-mlp`, and `turing` crashes because it's dependent on `turing-mlp`). So the only question is why `turing-postgresql-mlp` is pending. 

Can you post the output of: 
```shell
kubectl get statefulsets/turing-postgresql-mlp -o yaml
```

My assumption is that because you run it on your local machine, maybe you don't have enough resources (cpu/mem) to accommodate all the necessary Turing components. If it's true, then you have to either 1) scale up your cluster or 2) reduce resources requirements on Turing deployment

**Comment by ashwinath** [comment]
If you run `kubectl describe pod <pod name>`, under the `Events` section you should be able to see the reason for failure. Could you send the results of `kubectl describe pod turing-postgresql-mlp-0`?

**Comment by verramuktytoko** [comment]
@romanwozniak this is the output of
`kubectl get statefulsets/turing-postgresql-mlp -o yaml`

apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    meta.helm.sh/release-name: turing
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-11-29T08:25:49Z"
  generation: 1
  labels:
    app: postgresql-mlp
    app.kubernetes.io/managed-by: Helm
    chart: postgresql-8.9.8
    heritage: Helm
    release: turing
  name: turing-postgresql-mlp
  namespace: default
  resourceVersion: "4271"
  uid: 13e95212-1e07-413a-90d5-e0dba5c1f5aa
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: postgresql-mlp
      release: turing
      role: master
  serviceName: turing-postgresql-mlp-headless
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgresql-mlp
        chart: postgresql-8.9.8
        heritage: Helm
        release: turing
        role: master
      name: turing-postgresql-mlp
    spec:
      containers:
      - env:
        - name: BITNAMI_DEBUG
          value: "false"
        - name: POSTGRESQL_PORT_NUMBER
          value: "5432"
        - name: POSTGRESQL_VOLUME_DIR
          value: /bitnami/postgresql
        - name: PGDATA
          value: /bitnami/postgresql/data
        - name: POSTGRES_USER
          value: mlp
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgresql-password
              name: turing-postgresql-mlp
        - name: POSTGRES_DB
          value: mlp
        - name: POSTGRESQL_ENABLE_LDAP
          value: "no"
        image: docker.io/bitnami/postgresql:11.8.0-debian-10-r1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - exec pg_isready -U "mlp" -d "mlp" -h 127.0.0.1 -p 5432
          failureThreshold: 6
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: turing-postgresql-mlp
        ports:
        - containerPort: 5432
          name: tcp-postgresql
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - -e
            - |
              exec pg_isready -U "mlp" -d "mlp" -h 127.0.0.1 -p 5432
              [ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]
          failureThreshold: 6
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 500m
            memory: 256Mi
        securityContext:
          runAsUser: 1001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /bitnami/postgresql
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          medium: Memory
          sizeLimit: 1Gi
        name: dshm
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  collisionCount: 0
  currentReplicas: 1
  currentRevision: turing-postgresql-mlp-5c8ffd594f
  observedGeneration: 1
  replicas: 1
  updateRevision: turing-postgresql-mlp-5c8ffd594f
  updatedReplicas: 1

**Comment by verramuktytoko** [comment]
@ashwinath 

I think Roman's guess is correct, this is due to insufficient memory on my local.

```
Name:           turing-postgresql-mlp-0
Namespace:      default
Priority:       0
Node:           <none>
Labels:         app=postgresql-mlp
                chart=postgresql-8.9.8
                controller-revision-hash=turing-postgresql-mlp-5c8ffd594f
                heritage=Helm
                release=turing
                role=master
                statefulset.kubernetes.io/pod-name=turing-postgresql-mlp-0
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  StatefulSet/turing-postgresql-mlp
Containers:
  turing-postgresql-mlp:
    Image:      docker.io/bitnami/postgresql:11.8.0-debian-10-r1
    Port:       5432/TCP
    Host Port:  0/TCP
    Requests:
      cpu:      500m
      memory:   256Mi
    Liveness:   exec [/bin/sh -c exec pg_isready -U "mlp" -d "mlp" -h 127.0.0.1 -p 5432] delay=30s timeout=5s period=10s #success=1 #failure=6
    Readiness:  exec [/bin/sh -c -e exec pg_isready -U "mlp" -d "mlp" -h 127.0.0.1 -p 5432
[ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]
] delay=5s timeout=5s period=10s #success=1 #failure=6
    Environment:
      BITNAMI_DEBUG:           false
      POSTGRESQL_PORT_NUMBER:  5432
      POSTGRESQL_VOLUME_DIR:   /bitnami/postgresql
      PGDATA:                  /bitnami/postgresql/data
      POSTGRES_USER:           mlp
      POSTGRES_PASSWORD:       <set to the key 'postgresql-password' in secret 'turing-postgresql-mlp'>  Optional: false
      POSTGRES_DB:             mlp
      POSTGRESQL_ENABLE_LDAP:  no
    Mounts:
      /bitnami/postgresql from data (rw)
      /dev/shm from dshm (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-bvf92 (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-turing-postgresql-mlp-0
    ReadOnly:   false
  dshm:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  1Gi
  kube-api-access-bvf92:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  21h   default-scheduler  0/1 nodes are available: 1 Insufficient memory.
```

**Comment by romanwozniak** [comment]
@verramuktytoko as I suggested, you can try to scale (either vertically or horizontally) your local cluster and try it again. 
Otherwise, you can reduce the default resource configuration of the mlp components:

1. Create configuration file **values.yaml**:
```yaml
mlp:
   postgresql:
     resources:
       requests:
         memory: "128Mi"

merlin:
   postgresql:
     resources:
       requests:
         memory: "128Mi"

postgresql:
   resources:
     requests:
       memory: "128Mi"
```

2. Pass these values to helm during deployment:
```shell
helm install turing turing/turing --values values.yaml
```

You can learn more about the available configuration values here: https://github.com/gojek/turing/tree/main/infra/charts/turing

**Comment by verramuktytoko** [comment]
@romanwozniak 
I have scales up the machine, but there's still 1 crash pod.

```
NAME                                           READY   STATUS             RESTARTS   AGE
turing-vault-agent-injector-5976b6c65c-r4gb6   1/1     Running            0          3m13s
turing-vault-0                                 1/1     Running            0          3m13s
turing-postgresql-merlin-0                     1/1     Running            0          3m13s
turing-postgresql-0                            1/1     Running            0          3m13s
turing-postgresql-mlp-0                        1/1     Running            0          3m13s
turing-5d546c895d-fmqcf                        0/1     CrashLoopBackOff   4          3m13s
turing-mlp-7cc5f9bb94-4g67s                    1/1     Running            0          3m13s
turing-merlin-567844c58-m4tt4                  1/1     Running            0          3m13s
```

kubectl describe pod turing-5d546c895d-fmqcf

```
Name:         turing-5d546c895d-fmqcf
Namespace:    default
Priority:     0
Node:         k3d-mycluster-server-0/172.20.0.3
Start Time:   Tue, 30 Nov 2021 15:29:12 +0700
Labels:       app=turing
              pod-template-hash=5d546c895d
              release=turing
Annotations:  <none>
Status:       Running
IP:           10.42.0.22
IPs:
  IP:           10.42.0.22
Controlled By:  ReplicaSet/turing-5d546c895d
Containers:
  api:
    Container ID:  containerd://f11e36000a629b2b7a7093f2cdb56956248385e54baf5bd119d8fcfece3d0f1f
    Image:         ghcr.io/gojek/turing:v1.0.0
    Image ID:      ghcr.io/gojek/turing@sha256:f3c25574f290590d76bb25de461faa5b7d08a40bfae034239cf8ddfc6be39e04
    Port:          8080/TCP
    Host Port:     0/TCP
    Args:
      -config
      /etc/turing/config.yaml
      -ui-config
      /etc/turing/ui.config.json
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Tue, 30 Nov 2021 15:32:26 +0700
      Finished:     Tue, 30 Nov 2021 15:32:26 +0700
    Ready:          False
    Restart Count:  5
    Liveness:       http-get http://:8080/v1/internal/live delay=60s timeout=5s period=10s #success=1 #failure=3
    Readiness:      http-get http://:8080/v1/internal/ready delay=60s timeout=5s period=10s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /etc/turing from config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-tdlsj (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  turing-api-config
    Optional:    false
  kube-api-access-tdlsj:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  3m30s                  default-scheduler  Successfully assigned default/turing-5d546c895d-fmqcf to k3d-mycluster-server-0
  Normal   Pulling    3m30s                  kubelet            Pulling image "ghcr.io/gojek/turing:v1.0.0"
  Normal   Pulled     3m16s                  kubelet            Successfully pulled image "ghcr.io/gojek/turing:v1.0.0" in 13.709799337s
  Normal   Pulled     2m24s (x3 over 3m15s)  kubelet            Container image "ghcr.io/gojek/turing:v1.0.0" already present on machine
  Normal   Created    2m24s (x4 over 3m16s)  kubelet            Created container api
  Normal   Started    2m24s (x4 over 3m16s)  kubelet            Started container api
  Warning  BackOff    2m8s (x12 over 3m14s)  kubelet            Back-off restarting failed container
```

**Comment by verramuktytoko** [comment]
Another questions, if the turing installation has been successful, I can continue with this step **Start Turing API server** on this doc right https://github.com/gojek/turing?

**Comment by romanwozniak** [comment]
@verramuktytoko Can you please share the logs of a failed pod? 
Something like this would be helpful: 
```shell
kubectl logs deploy/turing
```

**Comment by romanwozniak** [comment]
> Another question, if the turing installation has been successful, I can continue with this step **Start Turing API server** on this doc right https://github.com/gojek/turing?

No, not really. This is a developers guide, i.e. if you want to build and run Turing from the source. Provided helm chart aims to simplify the deployment of Turing and its dependencies, so there is nothing else required to do once your deployment succeeded

**Comment by verramuktytoko** [comment]
kubectl logs deploy/turing

T```
uring UI config found at /etc/turing/ui.config.json...
Overriding UI config at ./turing-ui/app.config.js
Done.
Launching turing-api server:  ./turing-api -config /etc/turing/config.yaml
{"level":"panic","ts":1638264393.6378675,"caller":"server/application.go:50","msg":"Failed validating config: Key: 'Config.ClusterConfig.VaultConfig' Error:Field validation for 'VaultConfig' failed on the 'required_without' tag\nKey: 'Config.MLPConfig.MLPEncryptionKey' Error:Field validation for 'MLPEncryptionKey' failed on the 'required' tag","stacktrace":"github.com/gojek/turing/api/turing/log.Panicf\n\t/app/turing/log/log.go:59\ngithub.com/gojek/turing/api/turing/server.Run\n\t/app/turing/server/application.go:50\nmain.main\n\t/app/turing/cmd/main.go:9\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
panic: Failed validating config: Key: 'Config.ClusterConfig.VaultConfig' Error:Field validation for 'VaultConfig' failed on the 'required_without' tag
Key: 'Config.MLPConfig.MLPEncryptionKey' Error:Field validation for 'MLPEncryptionKey' failed on the 'required' tag

goroutine 1 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000544370, 0x0, 0x0, 0x0)
	/app/vendor/go.uber.org/zap/zapcore/entry.go:230 +0x545
go.uber.org/zap.(*SugaredLogger).log(0xc0000101a8, 0x2319204, 0x200a3fe, 0x1c, 0xc000807e48, 0x1, 0x1, 0x0, 0x0, 0x0)
	/app/vendor/go.uber.org/zap/sugar.go:234 +0x100
go.uber.org/zap.(*SugaredLogger).Panicf(...)
	/app/vendor/go.uber.org/zap/sugar.go:159
github.com/gojek/turing/api/turing/log.Panicf(...)
	/app/turing/log/log.go:59
github.com/gojek/turing/api/turing/server.Run()
	/app/turing/server/application.go:50 +0x267
main.main()
	/app/turing/cmd/main.go:9 +0x20
```

**Comment by verramuktytoko** [comment]
https://github.com/gojek/turing/issues/136#issuecomment-982411614
so the turing API server is automatically started after deployment is successful?
and we can directly create router, open turing UI http://host:3001/turing

**Comment by verramuktytoko** [comment]
> > Another question, if the turing installation has been successful, I can continue with this step **Start Turing API server** on this doc right https://github.com/gojek/turing?
> 
> No, not really. This is a developers guide, i.e. if you want to build and run Turing from the source. Provided helm chart aims to simplify the deployment of Turing and its dependencies, so there is nothing else required to do once your deployment succeeded

so the turing API server is automatically started after deployment is successful?
and we can directly create router, open turing UI http://host:3001/turing

**Comment by ashwinath** [comment]
@romanwozniak there's a small bug here: https://github.com/ashwinath/turing/blob/1648cd2dc270f25c7ae72aafed6dd1207733b2e5/infra/charts/turing/values.yaml#L278

Needs to have a default key, but user is recommended to override it.

@verramuktytoko For now the workaround is to set this value in your values.yaml. So it should look something like this now:

```yaml
mlp:
   postgresql:
     resources:
       requests:
         memory: "128Mi"

merlin:
   postgresql:
     resources:
       requests:
         memory: "128Mi"

postgresql:
   resources:
     requests:
       memory: "128Mi"

global:
  mlp:
    encryption:
      key: somevaluehere
```

**Comment by ashwinath** [comment]
> > > Another question, if the turing installation has been successful, I can continue with this step **Start Turing API server** on this doc right https://github.com/gojek/turing?
> > 
> > 
> > No, not really. This is a developers guide, i.e. if you want to build and run Turing from the source. Provided helm chart aims to simplify the deployment of Turing and its dependencies, so there is nothing else required to do once your deployment succeeded
> 
> so the turing API server is automatically started after deployment is successful? and we can directly create router, open turing UI http://host:3001/turing

Due to how Kubernetes work, this is not the case. If your Kubernetes setup allows for LoadBalancer service type, you should be able to get the external ip from istio-ingressgateway in `kubectl get service -n istio-system`. i.e. `echo "$(kubectl get svc -n istio-system | grep istio-ingressgateway | awk '{print $4}')/turing"`

**Comment by romanwozniak** [comment]
> @romanwozniak there's a small bug here: https://github.com/ashwinath/turing/blob/1648cd2dc270f25c7ae72aafed6dd1207733b2e5/infra/charts/turing/values.yaml#L278

Yes, it's included in the [values.minimal.yaml](https://github.com/gojek/turing/blob/main/infra/charts/turing/values.minimal.yaml), but I agree that we may set a default key for it as well.

@verramuktytoko Please take a look at [values.minimal.yaml](https://github.com/gojek/turing/blob/main/infra/charts/turing/values.minimal.yaml) as it may give you a better sense about what other config values you may need to tweak in your production deployment later on.

**Comment by romanwozniak** [comment]
> > > Another question, if the turing installation has been successful, I can continue with this step **Start Turing API server** on this doc right https://github.com/gojek/turing?
> > 
> > 
> > No, not really. This is a developers guide, i.e. if you want to build and run Turing from the source. Provided helm chart aims to simplify the deployment of Turing and its dependencies, so there is nothing else required to do once your deployment succeeded
> 
> so the turing API server is automatically started after deployment is successful? and we can directly create router, open turing UI http://host:3001/turing

You can also port-forward `istio-ingresgateway` to make the entire deployment accessible on your localhost:
```shell
kubectl -n istio-system port-forward istio-ingressgateaway 8080:80
```
With that, you'll be able to access Turing UI at localhost:8080/turing 

**Note:** in order to access Turing UIm you need to configure `oAuthClientId` and pass it here: https://github.com/gojek/turing/blob/9fff67e9749a595a5164072357bd23bdf5bb1f6b/infra/charts/turing/values.minimal.yaml#L4

See: https://developers.google.com/adwords/api/docs/guides/authentication#generate_oauth2_credentials

**Comment by verramuktytoko** [comment]
is it correct if I use values.yaml like this? should I change the key value?
```
global:
  mlp:
    encryption:
      key: somevaluehere
```

I still got the same deployment error. Steps that I executed
1. re-create cluster
2. re-install turing/init
3. re-install turing/turing using this command `helm install turing turing/turing --values values.yaml`

**Result**

```
NAME                                            READY   STATUS             RESTARTS   AGE
turing-init-spark-operator-webhook-init-7rmsw   0/1     Completed          0          15m
turing-init-spark-operator-5b89d6567d-fgczn     1/1     Running            0          15m
turing-init-init-84xzh                          0/1     Completed          0          15m
turing-vault-agent-injector-5976b6c65c-xwzcs    1/1     Running            0          9m52s
turing-vault-0                                  1/1     Running            0          9m52s
turing-postgresql-merlin-0                      1/1     Running            0          9m51s
turing-postgresql-mlp-0                         1/1     Running            0          9m51s
turing-postgresql-0                             1/1     Running            0          9m51s
turing-mlp-7cc5f9bb94-kkr2g                     1/1     Running            0          9m52s
turing-merlin-567844c58-gttbx                   1/1     Running            0          9m52s
turing-5d546c895d-wnvhl                         0/1     CrashLoopBackOff   6          9m52s
```

```
Turing UI config found at /etc/turing/ui.config.json...
Overriding UI config at ./turing-ui/app.config.js
Done.
Launching turing-api server:  ./turing-api -config /etc/turing/config.yaml
{"level":"panic","ts":1638326620.3388672,"caller":"server/application.go:50","msg":"Failed validating config: Key: 'Config.ClusterConfig.VaultConfig' Error:Field validation for 'VaultConfig' failed on the 'required_without' tag","stacktrace":"github.com/gojek/turing/api/turing/log.Panicf\n\t/app/turing/log/log.go:59\ngithub.com/gojek/turing/api/turing/server.Run\n\t/app/turing/server/application.go:50\nmain.main\n\t/app/turing/cmd/main.go:9\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
panic: Failed validating config: Key: 'Config.ClusterConfig.VaultConfig' Error:Field validation for 'VaultConfig' failed on the 'required_without' tag

goroutine 1 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000728840, 0x0, 0x0, 0x0)
	/app/vendor/go.uber.org/zap/zapcore/entry.go:230 +0x545
go.uber.org/zap.(*SugaredLogger).log(0xc000486040, 0x2319204, 0x200a3fe, 0x1c, 0xc00077de48, 0x1, 0x1, 0x0, 0x0, 0x0)
	/app/vendor/go.uber.org/zap/sugar.go:234 +0x100
go.uber.org/zap.(*SugaredLogger).Panicf(...)
	/app/vendor/go.uber.org/zap/sugar.go:159
github.com/gojek/turing/api/turing/log.Panicf(...)
	/app/turing/log/log.go:59
github.com/gojek/turing/api/turing/server.Run()
	/app/turing/server/application.go:50 +0x267
main.main()
	/app/turing/cmd/main.go:9 +0x20
```

**Comment by ashwinath** [comment]
> is it correct if I use values.yaml like this? should I change the key value?

You should change the values in `turing/infra/charts/turing/values.minimal.yaml` and use that as your values.yaml file.

As for the logs, why it's erroring out, it's due to a mistake in default values on our part. Could you override this value? `turing.clusterConfig.useInClusterConfig` should be `true`
