### ISSUE TITLE
Error in handling `Accept-Encoding`

### ISSUE THREAD

**Issue by ankurs** [gojek/turing#166]
We found an issue with how turing uses `Accept-Encoding`. We saw turing adding  `Accept-Encoding: gzip` to outbound requests, but not parsing the response as gzip. This results in clients calling turing receiving gzipped response even when they did not request for it.

Reproduction -> 
1. deploy a service that supports gzip response encoding
2. configure turing to route to that end point
3. make a request through Turing without setting `Accept-Encoding`

cc @peterjrichens

**Comment by romanwozniak** [comment]
Hi @ankurs, thanks for reporting this! After a quick scrolling through the codebase, I can't see that Turing explicitly adds any extra headers besides what is passed by the client. But the team will look into it and get back with more details soon.

**Comment by ankurs** [comment]
I have a feeling this might be because of https://github.com/gojek/fiber but haven't looking deeper into it
Please let me know if need any more info for this
