### ISSUE TITLE
Add more robust checks in Turing API config validation

### ISSUE THREAD

**Issue by davidheryanto** [gojek/turing#25]
Currently the validation for Config object in Turing API mostly checks for value presence only with `validate:required`
https://github.com/gojek/turing/blob/c0e775eb2b08c1ab4077a4ac252d186ff3ecbdd1/api/turing/config/config.go#L36-L40

However there are other validations we need to perform as well. For instance, making sure URL values follows valid URL syntax or that value for log level is only one of info,debug,warn etc.

More throrough config validation ensures config values are properly validated and any config value error is returned to the user as early as possible with clear error message.

**Comment by romanwozniak** [comment]
Closing as inactive
